### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [JaerenTredway/colmar_academy#5]
Grade: Exceeds expectations

Summary: Great job on this project, the sight looks very good. You used a lot of good techniques and kept your code well organized. Take a look at the issues I created for some best practice tweaks as well as some new techniques you can start looking into. Overall really well done, I hope you enjoyed the course!

Some future learning subjects to look into: SASS, CSS Grid, CSS variables, ARIA roles, SEO, javascript

**Comment by JaerenTredway** [comment]
thanks for the feedback!
